branch-defaults:
  default:
    environment: analytip-env1
environment-defaults:
  analytip-env1:
    branch: null
    repository: null
global:
  application_name: analytip
  default_ec2_keyname: Ank-Ram
  default_platform: python2.7
  default_region: us-west-2
  profile: eb-cli
  sc: null
