# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Info', models.TextField()),
                ('TimeStamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StartUpInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('TeamMemebersNumber', models.CharField(max_length=100)),
                ('About', models.TextField()),
                ('HeadQuarters', models.CharField(max_length=100)),
                ('ProductVideo', models.CharField(max_length=100)),
                ('WebsiteLink', models.CharField(max_length=100)),
                ('Founders', models.CharField(max_length=100)),
                ('FundingInfo', models.TextField()),
                ('Team', models.CharField(max_length=50)),
                ('ProductFeature', models.CharField(max_length=100)),
                ('DateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TechCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Info', models.CharField(max_length=100)),
                ('TimeStamp', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='startupinfo',
            name='TechSpecId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TechCategories'),
        ),
        migrations.AddField(
            model_name='activites',
            name='StartUpId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.StartUpInfo'),
        ),
    ]
